USE glowskin;

TRUNCATE TABLE product_reviews;

INSERT INTO product_reviews (user_id, product_id, rating, comment, created_at) VALUES
(1, 51, 5, 'Sangat puas, teksturnya ringan dan cepat meresap. Highly recommended!', DATE_SUB(NOW(), INTERVAL 4 DAY)),
(2, 51, 5, 'Packaging bagus, produk original. Sangat worth it!', DATE_SUB(NOW(), INTERVAL 32 DAY)),
(3, 51, 4, 'Produk ori dan sesuai deskripsi. Kulit membaik setelah 3 minggu.', DATE_SUB(NOW(), INTERVAL 18 DAY)),
(4, 51, 4, 'Cukup puas, kulit terasa lebih lembap. Mungkin akan beli lagi.', DATE_SUB(NOW(), INTERVAL 87 DAY)),
(5, 51, 5, 'Kulit yang kusam jadi lebih cerah dan segar. Suka banget!', DATE_SUB(NOW(), INTERVAL 12 DAY)),
(1, 52, 5, 'Setelah pakai ini kulit lebih kenyal dan sehat. Recommended!', DATE_SUB(NOW(), INTERVAL 55 DAY)),
(2, 52, 4, 'Produknya bagus dan efektif, hanya butuh waktu sedikit lebih lama.', DATE_SUB(NOW(), INTERVAL 4 DAY)),
(3, 52, 5, 'Sangat puas, teksturnya ringan dan cepat meresap. Highly recommended!', DATE_SUB(NOW(), INTERVAL 28 DAY)),
(4, 52, 3, 'Teksturnya agak berat untuk kulit berminyak, tapi tetap aman dipakai.', DATE_SUB(NOW(), INTERVAL 65 DAY)),
(5, 52, 4, 'Produknya bagus dan efektif, hanya butuh waktu sedikit lebih lama.', DATE_SUB(NOW(), INTERVAL 72 DAY)),
(1, 53, 4, 'Produk ori dan sesuai deskripsi. Kulit membaik setelah 3 minggu.', DATE_SUB(NOW(), INTERVAL 92 DAY)),
(2, 53, 5, 'Kulit yang kusam jadi lebih cerah dan segar. Suka banget!', DATE_SUB(NOW(), INTERVAL 54 DAY)),
(3, 53, 5, 'Hasilnya kelihatan setelah seminggu pemakaian rutin. Bakal beli lagi!', DATE_SUB(NOW(), INTERVAL 58 DAY)),
(4, 53, 4, 'Bagus meski harganya sedikit mahal. Tapi kualitasnya sepadan.', DATE_SUB(NOW(), INTERVAL 104 DAY)),
(5, 53, 4, 'Produknya bagus dan efektif, hanya butuh waktu sedikit lebih lama.', DATE_SUB(NOW(), INTERVAL 98 DAY)),
(1, 54, 5, 'Pembelian terbaik saya! Benar-benar mengubah kondisi kulit.', DATE_SUB(NOW(), INTERVAL 90 DAY)),
(2, 54, 5, 'Wajah jadi lebih glowing setelah pakai ini rutin. Terima kasih!', DATE_SUB(NOW(), INTERVAL 44 DAY)),
(3, 54, 5, 'Packaging bagus, produk original. Sangat worth it!', DATE_SUB(NOW(), INTERVAL 20 DAY)),
(4, 54, 4, 'Produk ori dan sesuai deskripsi. Kulit membaik setelah 3 minggu.', DATE_SUB(NOW(), INTERVAL 98 DAY)),
(5, 54, 3, 'Belum ada perubahan signifikan. Mungkin perlu waktu lebih lama.', DATE_SUB(NOW(), INTERVAL 14 DAY)),
(1, 55, 4, 'Cukup puas, kulit terasa lebih lembap. Mungkin akan beli lagi.', DATE_SUB(NOW(), INTERVAL 49 DAY)),
(2, 55, 4, 'Cukup puas, kulit terasa lebih lembap. Mungkin akan beli lagi.', DATE_SUB(NOW(), INTERVAL 46 DAY)),
(3, 55, 5, 'Paling cocok di kulit sensitif saya. Tidak iritasi sama sekali.', DATE_SUB(NOW(), INTERVAL 78 DAY)),
(4, 55, 5, 'Packaging bagus, produk original. Sangat worth it!', DATE_SUB(NOW(), INTERVAL 104 DAY)),
(5, 55, 4, 'Produknya bagus dan efektif, hanya butuh waktu sedikit lebih lama.', DATE_SUB(NOW(), INTERVAL 94 DAY)),
(1, 56, 5, 'Langsung terasa bedanya dari pemakaian pertama. Serum favorit baru!', DATE_SUB(NOW(), INTERVAL 69 DAY)),
(2, 56, 3, 'Produknya oke, tapi hasilnya belum terlalu kelihatan di minggu pertama.', DATE_SUB(NOW(), INTERVAL 119 DAY)),
(3, 56, 4, 'Manfaatnya terasa nyata meski butuh konsistensi. Overall worth it.', DATE_SUB(NOW(), INTERVAL 11 DAY)),
(4, 56, 5, 'Kulit yang kusam jadi lebih cerah dan segar. Suka banget!', DATE_SUB(NOW(), INTERVAL 38 DAY)),
(5, 56, 4, 'Suka dengan kandungannya, cocok di kulit kombinasi.', DATE_SUB(NOW(), INTERVAL 74 DAY)),
(1, 57, 4, 'Produk ori dan sesuai deskripsi. Kulit membaik setelah 3 minggu.', DATE_SUB(NOW(), INTERVAL 91 DAY)),
(2, 57, 5, 'Sangat puas, teksturnya ringan dan cepat meresap. Highly recommended!', DATE_SUB(NOW(), INTERVAL 6 DAY)),
(3, 57, 4, 'Produk ori dan sesuai deskripsi. Kulit membaik setelah 3 minggu.', DATE_SUB(NOW(), INTERVAL 99 DAY)),
(4, 57, 4, 'Bagus meski harganya sedikit mahal. Tapi kualitasnya sepadan.', DATE_SUB(NOW(), INTERVAL 11 DAY)),
(5, 57, 5, 'Hasilnya kelihatan setelah seminggu pemakaian rutin. Bakal beli lagi!', DATE_SUB(NOW(), INTERVAL 111 DAY)),
(1, 58, 5, 'Sangat puas, teksturnya ringan dan cepat meresap. Highly recommended!', DATE_SUB(NOW(), INTERVAL 49 DAY)),
(2, 58, 5, 'Packaging bagus, produk original. Sangat worth it!', DATE_SUB(NOW(), INTERVAL 59 DAY)),
(3, 58, 3, 'Belum ada perubahan signifikan. Mungkin perlu waktu lebih lama.', DATE_SUB(NOW(), INTERVAL 21 DAY)),
(4, 58, 4, 'Suka dengan kandungannya, cocok di kulit kombinasi.', DATE_SUB(NOW(), INTERVAL 46 DAY)),
(5, 58, 5, 'Hasilnya kelihatan setelah seminggu pemakaian rutin. Bakal beli lagi!', DATE_SUB(NOW(), INTERVAL 86 DAY)),
(1, 59, 4, 'Bagus meski harganya sedikit mahal. Tapi kualitasnya sepadan.', DATE_SUB(NOW(), INTERVAL 90 DAY)),
(2, 59, 4, 'Cukup puas, kulit terasa lebih lembap. Mungkin akan beli lagi.', DATE_SUB(NOW(), INTERVAL 78 DAY)),
(3, 59, 4, 'Teksturnya ringan dan mudah meresap. Cocok untuk pemakaian sehari-hari.', DATE_SUB(NOW(), INTERVAL 69 DAY)),
(4, 59, 5, 'Hasilnya kelihatan setelah seminggu pemakaian rutin. Bakal beli lagi!', DATE_SUB(NOW(), INTERVAL 21 DAY)),
(5, 59, 5, 'Langsung terasa bedanya dari pemakaian pertama. Serum favorit baru!', DATE_SUB(NOW(), INTERVAL 49 DAY)),
(1, 60, 5, 'Packaging bagus, produk original. Sangat worth it!', DATE_SUB(NOW(), INTERVAL 119 DAY)),
(2, 60, 4, 'Produk ori dan sesuai deskripsi. Kulit membaik setelah 3 minggu.', DATE_SUB(NOW(), INTERVAL 88 DAY)),
(3, 60, 5, 'Paling cocok di kulit sensitif saya. Tidak iritasi sama sekali.', DATE_SUB(NOW(), INTERVAL 108 DAY)),
(4, 60, 5, 'Produk ini luar biasa! Kulit terasa lebih lembap dan cerah setelah 2 minggu.', DATE_SUB(NOW(), INTERVAL 30 DAY)),
(5, 60, 3, 'Produknya oke, tapi hasilnya belum terlalu kelihatan di minggu pertama.', DATE_SUB(NOW(), INTERVAL 104 DAY)),
(1, 61, 5, 'Paling cocok di kulit sensitif saya. Tidak iritasi sama sekali.', DATE_SUB(NOW(), INTERVAL 52 DAY)),
(2, 61, 5, 'Packaging bagus, produk original. Sangat worth it!', DATE_SUB(NOW(), INTERVAL 9 DAY)),
(3, 61, 4, 'Produk ori dan sesuai deskripsi. Kulit membaik setelah 3 minggu.', DATE_SUB(NOW(), INTERVAL 117 DAY)),
(4, 61, 4, 'Suka dengan kandungannya, cocok di kulit kombinasi.', DATE_SUB(NOW(), INTERVAL 28 DAY)),
(5, 61, 5, 'Langsung terasa bedanya dari pemakaian pertama. Serum favorit baru!', DATE_SUB(NOW(), INTERVAL 51 DAY)),
(1, 62, 5, 'Langsung terasa bedanya dari pemakaian pertama. Serum favorit baru!', DATE_SUB(NOW(), INTERVAL 19 DAY)),
(2, 62, 4, 'Bagus meski harganya sedikit mahal. Tapi kualitasnya sepadan.', DATE_SUB(NOW(), INTERVAL 18 DAY)),
(3, 62, 5, 'Hasilnya kelihatan setelah seminggu pemakaian rutin. Bakal beli lagi!', DATE_SUB(NOW(), INTERVAL 96 DAY)),
(4, 62, 3, 'Lumayan bagus, tapi ada produk lain dengan harga sama yang lebih efektif.', DATE_SUB(NOW(), INTERVAL 69 DAY)),
(5, 62, 4, 'Bagus meski harganya sedikit mahal. Tapi kualitasnya sepadan.', DATE_SUB(NOW(), INTERVAL 96 DAY)),
(1, 63, 4, 'Manfaatnya terasa nyata meski butuh konsistensi. Overall worth it.', DATE_SUB(NOW(), INTERVAL 115 DAY)),
(2, 63, 5, 'Setelah pakai ini kulit lebih kenyal dan sehat. Recommended!', DATE_SUB(NOW(), INTERVAL 52 DAY)),
(3, 63, 5, 'Paling cocok di kulit sensitif saya. Tidak iritasi sama sekali.', DATE_SUB(NOW(), INTERVAL 29 DAY)),
(4, 63, 4, 'Teksturnya ringan dan mudah meresap. Cocok untuk pemakaian sehari-hari.', DATE_SUB(NOW(), INTERVAL 66 DAY)),
(5, 63, 4, 'Kulit lebih terhidrasi setelah pemakaian rutin. Lanjut order!', DATE_SUB(NOW(), INTERVAL 12 DAY)),
(1, 64, 5, 'Produk ini luar biasa! Kulit terasa lebih lembap dan cerah setelah 2 minggu.', DATE_SUB(NOW(), INTERVAL 111 DAY)),
(2, 64, 5, 'Sangat puas, teksturnya ringan dan cepat meresap. Highly recommended!', DATE_SUB(NOW(), INTERVAL 20 DAY)),
(3, 64, 5, 'Pembelian terbaik saya! Benar-benar mengubah kondisi kulit.', DATE_SUB(NOW(), INTERVAL 102 DAY)),
(4, 64, 4, 'Manfaatnya terasa nyata meski butuh konsistensi. Overall worth it.', DATE_SUB(NOW(), INTERVAL 77 DAY)),
(5, 64, 3, 'Produknya oke, tapi hasilnya belum terlalu kelihatan di minggu pertama.', DATE_SUB(NOW(), INTERVAL 50 DAY)),
(1, 65, 4, 'Manfaatnya terasa nyata meski butuh konsistensi. Overall worth it.', DATE_SUB(NOW(), INTERVAL 77 DAY)),
(2, 65, 4, 'Kulit lebih terhidrasi setelah pemakaian rutin. Lanjut order!', DATE_SUB(NOW(), INTERVAL 68 DAY)),
(3, 65, 5, 'Packaging bagus, produk original. Sangat worth it!', DATE_SUB(NOW(), INTERVAL 71 DAY)),
(4, 65, 5, 'Produk ini luar biasa! Kulit terasa lebih lembap dan cerah setelah 2 minggu.', DATE_SUB(NOW(), INTERVAL 88 DAY)),
(5, 65, 4, 'Cukup puas, kulit terasa lebih lembap. Mungkin akan beli lagi.', DATE_SUB(NOW(), INTERVAL 88 DAY)),
(1, 66, 5, 'Kulit yang kusam jadi lebih cerah dan segar. Suka banget!', DATE_SUB(NOW(), INTERVAL 97 DAY)),
(2, 66, 3, 'Belum ada perubahan signifikan. Mungkin perlu waktu lebih lama.', DATE_SUB(NOW(), INTERVAL 99 DAY)),
(3, 66, 4, 'Suka dengan kandungannya, cocok di kulit kombinasi.', DATE_SUB(NOW(), INTERVAL 15 DAY)),
(4, 66, 5, 'Packaging bagus, produk original. Sangat worth it!', DATE_SUB(NOW(), INTERVAL 56 DAY)),
(5, 66, 4, 'Teksturnya ringan dan mudah meresap. Cocok untuk pemakaian sehari-hari.', DATE_SUB(NOW(), INTERVAL 59 DAY)),
(1, 67, 4, 'Produknya bagus dan efektif, hanya butuh waktu sedikit lebih lama.', DATE_SUB(NOW(), INTERVAL 93 DAY)),
(2, 67, 5, 'Packaging bagus, produk original. Sangat worth it!', DATE_SUB(NOW(), INTERVAL 65 DAY)),
(3, 67, 4, 'Teksturnya ringan dan mudah meresap. Cocok untuk pemakaian sehari-hari.', DATE_SUB(NOW(), INTERVAL 65 DAY)),
(4, 67, 4, 'Cukup puas, kulit terasa lebih lembap. Mungkin akan beli lagi.', DATE_SUB(NOW(), INTERVAL 112 DAY)),
(5, 67, 5, 'Packaging bagus, produk original. Sangat worth it!', DATE_SUB(NOW(), INTERVAL 108 DAY)),
(1, 68, 5, 'Kulit yang kusam jadi lebih cerah dan segar. Suka banget!', DATE_SUB(NOW(), INTERVAL 78 DAY)),
(2, 68, 5, 'Hasilnya kelihatan setelah seminggu pemakaian rutin. Bakal beli lagi!', DATE_SUB(NOW(), INTERVAL 20 DAY)),
(3, 68, 3, 'Belum ada perubahan signifikan. Mungkin perlu waktu lebih lama.', DATE_SUB(NOW(), INTERVAL 98 DAY)),
(4, 68, 4, 'Teksturnya ringan dan mudah meresap. Cocok untuk pemakaian sehari-hari.', DATE_SUB(NOW(), INTERVAL 70 DAY)),
(5, 68, 5, 'Kulit yang kusam jadi lebih cerah dan segar. Suka banget!', DATE_SUB(NOW(), INTERVAL 118 DAY)),
(1, 69, 4, 'Produknya bagus dan efektif, hanya butuh waktu sedikit lebih lama.', DATE_SUB(NOW(), INTERVAL 77 DAY)),
(2, 69, 4, 'Suka dengan kandungannya, cocok di kulit kombinasi.', DATE_SUB(NOW(), INTERVAL 63 DAY)),
(3, 69, 4, 'Produknya bagus dan efektif, hanya butuh waktu sedikit lebih lama.', DATE_SUB(NOW(), INTERVAL 15 DAY)),
(4, 69, 5, 'Paling cocok di kulit sensitif saya. Tidak iritasi sama sekali.', DATE_SUB(NOW(), INTERVAL 113 DAY)),
(5, 69, 5, 'Packaging bagus, produk original. Sangat worth it!', DATE_SUB(NOW(), INTERVAL 31 DAY)),
(1, 70, 5, 'Produk ini luar biasa! Kulit terasa lebih lembap dan cerah setelah 2 minggu.', DATE_SUB(NOW(), INTERVAL 31 DAY)),
(2, 70, 4, 'Cukup puas, kulit terasa lebih lembap. Mungkin akan beli lagi.', DATE_SUB(NOW(), INTERVAL 11 DAY)),
(3, 70, 5, 'Langsung terasa bedanya dari pemakaian pertama. Serum favorit baru!', DATE_SUB(NOW(), INTERVAL 105 DAY)),
(4, 70, 5, 'Sangat puas, teksturnya ringan dan cepat meresap. Highly recommended!', DATE_SUB(NOW(), INTERVAL 98 DAY)),
(5, 70, 3, 'Lumayan bagus, tapi ada produk lain dengan harga sama yang lebih efektif.', DATE_SUB(NOW(), INTERVAL 99 DAY)),
(1, 71, 5, 'Pembelian terbaik saya! Benar-benar mengubah kondisi kulit.', DATE_SUB(NOW(), INTERVAL 17 DAY)),
(2, 71, 5, 'Langsung terasa bedanya dari pemakaian pertama. Serum favorit baru!', DATE_SUB(NOW(), INTERVAL 71 DAY)),
(3, 71, 4, 'Teksturnya ringan dan mudah meresap. Cocok untuk pemakaian sehari-hari.', DATE_SUB(NOW(), INTERVAL 34 DAY)),
(4, 71, 4, 'Manfaatnya terasa nyata meski butuh konsistensi. Overall worth it.', DATE_SUB(NOW(), INTERVAL 28 DAY)),
(5, 71, 5, 'Kulit yang kusam jadi lebih cerah dan segar. Suka banget!', DATE_SUB(NOW(), INTERVAL 97 DAY)),
(1, 72, 5, 'Hasilnya kelihatan setelah seminggu pemakaian rutin. Bakal beli lagi!', DATE_SUB(NOW(), INTERVAL 92 DAY)),
(2, 72, 4, 'Bagus meski harganya sedikit mahal. Tapi kualitasnya sepadan.', DATE_SUB(NOW(), INTERVAL 52 DAY)),
(3, 72, 5, 'Paling cocok di kulit sensitif saya. Tidak iritasi sama sekali.', DATE_SUB(NOW(), INTERVAL 57 DAY)),
(4, 72, 3, 'Lumayan bagus, tapi ada produk lain dengan harga sama yang lebih efektif.', DATE_SUB(NOW(), INTERVAL 58 DAY)),
(5, 72, 4, 'Cukup puas, kulit terasa lebih lembap. Mungkin akan beli lagi.', DATE_SUB(NOW(), INTERVAL 32 DAY)),
(1, 73, 4, 'Produk ori dan sesuai deskripsi. Kulit membaik setelah 3 minggu.', DATE_SUB(NOW(), INTERVAL 9 DAY)),
(2, 73, 5, 'Paling cocok di kulit sensitif saya. Tidak iritasi sama sekali.', DATE_SUB(NOW(), INTERVAL 3 DAY)),
(3, 73, 5, 'Setelah pakai ini kulit lebih kenyal dan sehat. Recommended!', DATE_SUB(NOW(), INTERVAL 71 DAY)),
(4, 73, 4, 'Produk ori dan sesuai deskripsi. Kulit membaik setelah 3 minggu.', DATE_SUB(NOW(), INTERVAL 76 DAY)),
(5, 73, 4, 'Produk ori dan sesuai deskripsi. Kulit membaik setelah 3 minggu.', DATE_SUB(NOW(), INTERVAL 1 DAY)),
(1, 74, 5, 'Sangat puas, teksturnya ringan dan cepat meresap. Highly recommended!', DATE_SUB(NOW(), INTERVAL 91 DAY)),
(2, 74, 5, 'Produk ini luar biasa! Kulit terasa lebih lembap dan cerah setelah 2 minggu.', DATE_SUB(NOW(), INTERVAL 30 DAY)),
(3, 74, 5, 'Sangat puas, teksturnya ringan dan cepat meresap. Highly recommended!', DATE_SUB(NOW(), INTERVAL 116 DAY)),
(4, 74, 4, 'Produknya bagus dan efektif, hanya butuh waktu sedikit lebih lama.', DATE_SUB(NOW(), INTERVAL 111 DAY)),
(5, 74, 3, 'Belum ada perubahan signifikan. Mungkin perlu waktu lebih lama.', DATE_SUB(NOW(), INTERVAL 10 DAY)),
(1, 75, 4, 'Produk ori dan sesuai deskripsi. Kulit membaik setelah 3 minggu.', DATE_SUB(NOW(), INTERVAL 36 DAY)),
(2, 75, 4, 'Kulit lebih terhidrasi setelah pemakaian rutin. Lanjut order!', DATE_SUB(NOW(), INTERVAL 28 DAY)),
(3, 75, 5, 'Kulit yang kusam jadi lebih cerah dan segar. Suka banget!', DATE_SUB(NOW(), INTERVAL 17 DAY)),
(4, 75, 5, 'Setelah pakai ini kulit lebih kenyal dan sehat. Recommended!', DATE_SUB(NOW(), INTERVAL 74 DAY)),
(5, 75, 4, 'Kulit lebih terhidrasi setelah pemakaian rutin. Lanjut order!', DATE_SUB(NOW(), INTERVAL 32 DAY)),
(1, 76, 5, 'Langsung terasa bedanya dari pemakaian pertama. Serum favorit baru!', DATE_SUB(NOW(), INTERVAL 104 DAY)),
(2, 76, 3, 'Produknya original, tapi scent-nya kurang cocok di preferensi saya.', DATE_SUB(NOW(), INTERVAL 25 DAY)),
(3, 76, 4, 'Cukup puas, kulit terasa lebih lembap. Mungkin akan beli lagi.', DATE_SUB(NOW(), INTERVAL 13 DAY)),
(4, 76, 5, 'Wajah jadi lebih glowing setelah pakai ini rutin. Terima kasih!', DATE_SUB(NOW(), INTERVAL 46 DAY)),
(5, 76, 4, 'Manfaatnya terasa nyata meski butuh konsistensi. Overall worth it.', DATE_SUB(NOW(), INTERVAL 53 DAY)),
(1, 77, 4, 'Kulit lebih terhidrasi setelah pemakaian rutin. Lanjut order!', DATE_SUB(NOW(), INTERVAL 111 DAY)),
(2, 77, 5, 'Produk ini luar biasa! Kulit terasa lebih lembap dan cerah setelah 2 minggu.', DATE_SUB(NOW(), INTERVAL 87 DAY)),
(3, 77, 4, 'Cukup puas, kulit terasa lebih lembap. Mungkin akan beli lagi.', DATE_SUB(NOW(), INTERVAL 8 DAY)),
(4, 77, 4, 'Manfaatnya terasa nyata meski butuh konsistensi. Overall worth it.', DATE_SUB(NOW(), INTERVAL 94 DAY)),
(5, 77, 5, 'Paling cocok di kulit sensitif saya. Tidak iritasi sama sekali.', DATE_SUB(NOW(), INTERVAL 103 DAY)),
(1, 78, 5, 'Sangat puas, teksturnya ringan dan cepat meresap. Highly recommended!', DATE_SUB(NOW(), INTERVAL 32 DAY)),
(2, 78, 5, 'Hasilnya kelihatan setelah seminggu pemakaian rutin. Bakal beli lagi!', DATE_SUB(NOW(), INTERVAL 25 DAY)),
(3, 78, 3, 'Lumayan bagus, tapi ada produk lain dengan harga sama yang lebih efektif.', DATE_SUB(NOW(), INTERVAL 58 DAY)),
(4, 78, 4, 'Teksturnya ringan dan mudah meresap. Cocok untuk pemakaian sehari-hari.', DATE_SUB(NOW(), INTERVAL 55 DAY)),
(5, 78, 5, 'Pembelian terbaik saya! Benar-benar mengubah kondisi kulit.', DATE_SUB(NOW(), INTERVAL 36 DAY)),
(1, 79, 4, 'Kulit lebih terhidrasi setelah pemakaian rutin. Lanjut order!', DATE_SUB(NOW(), INTERVAL 32 DAY)),
(2, 79, 4, 'Cukup puas, kulit terasa lebih lembap. Mungkin akan beli lagi.', DATE_SUB(NOW(), INTERVAL 57 DAY)),
(3, 79, 4, 'Cukup puas, kulit terasa lebih lembap. Mungkin akan beli lagi.', DATE_SUB(NOW(), INTERVAL 7 DAY)),
(4, 79, 5, 'Kulit yang kusam jadi lebih cerah dan segar. Suka banget!', DATE_SUB(NOW(), INTERVAL 108 DAY)),
(5, 79, 5, 'Produk ini luar biasa! Kulit terasa lebih lembap dan cerah setelah 2 minggu.', DATE_SUB(NOW(), INTERVAL 12 DAY)),
(1, 80, 5, 'Hasilnya kelihatan setelah seminggu pemakaian rutin. Bakal beli lagi!', DATE_SUB(NOW(), INTERVAL 22 DAY)),
(2, 80, 4, 'Manfaatnya terasa nyata meski butuh konsistensi. Overall worth it.', DATE_SUB(NOW(), INTERVAL 63 DAY)),
(3, 80, 5, 'Langsung terasa bedanya dari pemakaian pertama. Serum favorit baru!', DATE_SUB(NOW(), INTERVAL 28 DAY)),
(4, 80, 5, 'Wajah jadi lebih glowing setelah pakai ini rutin. Terima kasih!', DATE_SUB(NOW(), INTERVAL 116 DAY)),
(5, 80, 3, 'Produknya oke, tapi hasilnya belum terlalu kelihatan di minggu pertama.', DATE_SUB(NOW(), INTERVAL 22 DAY)),
(1, 81, 5, 'Wajah jadi lebih glowing setelah pakai ini rutin. Terima kasih!', DATE_SUB(NOW(), INTERVAL 1 DAY)),
(2, 81, 5, 'Wajah jadi lebih glowing setelah pakai ini rutin. Terima kasih!', DATE_SUB(NOW(), INTERVAL 34 DAY)),
(3, 81, 4, 'Kulit lebih terhidrasi setelah pemakaian rutin. Lanjut order!', DATE_SUB(NOW(), INTERVAL 37 DAY)),
(4, 81, 4, 'Manfaatnya terasa nyata meski butuh konsistensi. Overall worth it.', DATE_SUB(NOW(), INTERVAL 90 DAY)),
(5, 81, 5, 'Kulit yang kusam jadi lebih cerah dan segar. Suka banget!', DATE_SUB(NOW(), INTERVAL 85 DAY)),
(1, 82, 5, 'Langsung terasa bedanya dari pemakaian pertama. Serum favorit baru!', DATE_SUB(NOW(), INTERVAL 20 DAY)),
(2, 82, 4, 'Produk ori dan sesuai deskripsi. Kulit membaik setelah 3 minggu.', DATE_SUB(NOW(), INTERVAL 38 DAY)),
(3, 82, 5, 'Hasilnya kelihatan setelah seminggu pemakaian rutin. Bakal beli lagi!', DATE_SUB(NOW(), INTERVAL 8 DAY)),
(4, 82, 3, 'Lumayan bagus, tapi ada produk lain dengan harga sama yang lebih efektif.', DATE_SUB(NOW(), INTERVAL 95 DAY)),
(5, 82, 4, 'Produknya bagus dan efektif, hanya butuh waktu sedikit lebih lama.', DATE_SUB(NOW(), INTERVAL 96 DAY)),
(1, 83, 4, 'Suka dengan kandungannya, cocok di kulit kombinasi.', DATE_SUB(NOW(), INTERVAL 8 DAY)),
(2, 83, 5, 'Produk ini luar biasa! Kulit terasa lebih lembap dan cerah setelah 2 minggu.', DATE_SUB(NOW(), INTERVAL 75 DAY)),
(3, 83, 5, 'Langsung terasa bedanya dari pemakaian pertama. Serum favorit baru!', DATE_SUB(NOW(), INTERVAL 65 DAY)),
(4, 83, 4, 'Teksturnya ringan dan mudah meresap. Cocok untuk pemakaian sehari-hari.', DATE_SUB(NOW(), INTERVAL 8 DAY)),
(5, 83, 4, 'Cukup puas, kulit terasa lebih lembap. Mungkin akan beli lagi.', DATE_SUB(NOW(), INTERVAL 109 DAY)),
(1, 84, 5, 'Pembelian terbaik saya! Benar-benar mengubah kondisi kulit.', DATE_SUB(NOW(), INTERVAL 9 DAY)),
(2, 84, 5, 'Setelah pakai ini kulit lebih kenyal dan sehat. Recommended!', DATE_SUB(NOW(), INTERVAL 9 DAY)),
(3, 84, 5, 'Hasilnya kelihatan setelah seminggu pemakaian rutin. Bakal beli lagi!', DATE_SUB(NOW(), INTERVAL 52 DAY)),
(4, 84, 4, 'Cukup puas, kulit terasa lebih lembap. Mungkin akan beli lagi.', DATE_SUB(NOW(), INTERVAL 114 DAY)),
(5, 84, 3, 'Lumayan bagus, tapi ada produk lain dengan harga sama yang lebih efektif.', DATE_SUB(NOW(), INTERVAL 32 DAY)),
(1, 85, 4, 'Produknya bagus dan efektif, hanya butuh waktu sedikit lebih lama.', DATE_SUB(NOW(), INTERVAL 80 DAY)),
(2, 85, 4, 'Cukup puas, kulit terasa lebih lembap. Mungkin akan beli lagi.', DATE_SUB(NOW(), INTERVAL 54 DAY)),
(3, 85, 5, 'Setelah pakai ini kulit lebih kenyal dan sehat. Recommended!', DATE_SUB(NOW(), INTERVAL 73 DAY)),
(4, 85, 5, 'Kulit yang kusam jadi lebih cerah dan segar. Suka banget!', DATE_SUB(NOW(), INTERVAL 41 DAY)),
(5, 85, 4, 'Bagus meski harganya sedikit mahal. Tapi kualitasnya sepadan.', DATE_SUB(NOW(), INTERVAL 27 DAY)),
(1, 86, 5, 'Paling cocok di kulit sensitif saya. Tidak iritasi sama sekali.', DATE_SUB(NOW(), INTERVAL 31 DAY)),
(2, 86, 3, 'Belum ada perubahan signifikan. Mungkin perlu waktu lebih lama.', DATE_SUB(NOW(), INTERVAL 51 DAY)),
(3, 86, 4, 'Teksturnya ringan dan mudah meresap. Cocok untuk pemakaian sehari-hari.', DATE_SUB(NOW(), INTERVAL 86 DAY)),
(4, 86, 5, 'Packaging bagus, produk original. Sangat worth it!', DATE_SUB(NOW(), INTERVAL 59 DAY)),
(5, 86, 4, 'Suka dengan kandungannya, cocok di kulit kombinasi.', DATE_SUB(NOW(), INTERVAL 119 DAY)),
(1, 87, 4, 'Cukup puas, kulit terasa lebih lembap. Mungkin akan beli lagi.', DATE_SUB(NOW(), INTERVAL 2 DAY)),
(2, 87, 5, 'Langsung terasa bedanya dari pemakaian pertama. Serum favorit baru!', DATE_SUB(NOW(), INTERVAL 80 DAY)),
(3, 87, 4, 'Cukup puas, kulit terasa lebih lembap. Mungkin akan beli lagi.', DATE_SUB(NOW(), INTERVAL 10 DAY)),
(4, 87, 4, 'Produk ori dan sesuai deskripsi. Kulit membaik setelah 3 minggu.', DATE_SUB(NOW(), INTERVAL 65 DAY)),
(5, 87, 5, 'Packaging bagus, produk original. Sangat worth it!', DATE_SUB(NOW(), INTERVAL 17 DAY)),
(1, 88, 5, 'Paling cocok di kulit sensitif saya. Tidak iritasi sama sekali.', DATE_SUB(NOW(), INTERVAL 113 DAY)),
(2, 88, 5, 'Sangat puas, teksturnya ringan dan cepat meresap. Highly recommended!', DATE_SUB(NOW(), INTERVAL 113 DAY)),
(3, 88, 3, 'Teksturnya agak berat untuk kulit berminyak, tapi tetap aman dipakai.', DATE_SUB(NOW(), INTERVAL 48 DAY)),
(4, 88, 4, 'Bagus meski harganya sedikit mahal. Tapi kualitasnya sepadan.', DATE_SUB(NOW(), INTERVAL 21 DAY)),
(5, 88, 5, 'Langsung terasa bedanya dari pemakaian pertama. Serum favorit baru!', DATE_SUB(NOW(), INTERVAL 107 DAY)),
(1, 89, 4, 'Bagus meski harganya sedikit mahal. Tapi kualitasnya sepadan.', DATE_SUB(NOW(), INTERVAL 79 DAY)),
(2, 89, 4, 'Produknya bagus dan efektif, hanya butuh waktu sedikit lebih lama.', DATE_SUB(NOW(), INTERVAL 86 DAY)),
(3, 89, 4, 'Bagus meski harganya sedikit mahal. Tapi kualitasnya sepadan.', DATE_SUB(NOW(), INTERVAL 120 DAY)),
(4, 89, 5, 'Sangat puas, teksturnya ringan dan cepat meresap. Highly recommended!', DATE_SUB(NOW(), INTERVAL 113 DAY)),
(5, 89, 5, 'Pembelian terbaik saya! Benar-benar mengubah kondisi kulit.', DATE_SUB(NOW(), INTERVAL 34 DAY)),
(1, 90, 5, 'Sangat puas, teksturnya ringan dan cepat meresap. Highly recommended!', DATE_SUB(NOW(), INTERVAL 114 DAY)),
(2, 90, 4, 'Cukup puas, kulit terasa lebih lembap. Mungkin akan beli lagi.', DATE_SUB(NOW(), INTERVAL 96 DAY)),
(3, 90, 5, 'Kulit yang kusam jadi lebih cerah dan segar. Suka banget!', DATE_SUB(NOW(), INTERVAL 20 DAY)),
(4, 90, 5, 'Packaging bagus, produk original. Sangat worth it!', DATE_SUB(NOW(), INTERVAL 37 DAY)),
(5, 90, 3, 'Lumayan bagus, tapi ada produk lain dengan harga sama yang lebih efektif.', DATE_SUB(NOW(), INTERVAL 27 DAY)),
(1, 91, 5, 'Paling cocok di kulit sensitif saya. Tidak iritasi sama sekali.', DATE_SUB(NOW(), INTERVAL 27 DAY)),
(2, 91, 5, 'Packaging bagus, produk original. Sangat worth it!', DATE_SUB(NOW(), INTERVAL 65 DAY)),
(3, 91, 4, 'Kulit lebih terhidrasi setelah pemakaian rutin. Lanjut order!', DATE_SUB(NOW(), INTERVAL 33 DAY)),
(4, 91, 4, 'Produknya bagus dan efektif, hanya butuh waktu sedikit lebih lama.', DATE_SUB(NOW(), INTERVAL 12 DAY)),
(5, 91, 5, 'Wajah jadi lebih glowing setelah pakai ini rutin. Terima kasih!', DATE_SUB(NOW(), INTERVAL 107 DAY)),
(1, 92, 5, 'Packaging bagus, produk original. Sangat worth it!', DATE_SUB(NOW(), INTERVAL 6 DAY)),
(2, 92, 4, 'Produknya bagus dan efektif, hanya butuh waktu sedikit lebih lama.', DATE_SUB(NOW(), INTERVAL 43 DAY)),
(3, 92, 5, 'Pembelian terbaik saya! Benar-benar mengubah kondisi kulit.', DATE_SUB(NOW(), INTERVAL 82 DAY)),
(4, 92, 3, 'Belum ada perubahan signifikan. Mungkin perlu waktu lebih lama.', DATE_SUB(NOW(), INTERVAL 21 DAY)),
(5, 92, 4, 'Kulit lebih terhidrasi setelah pemakaian rutin. Lanjut order!', DATE_SUB(NOW(), INTERVAL 71 DAY)),
(1, 93, 4, 'Manfaatnya terasa nyata meski butuh konsistensi. Overall worth it.', DATE_SUB(NOW(), INTERVAL 72 DAY)),
(2, 93, 5, 'Produk ini luar biasa! Kulit terasa lebih lembap dan cerah setelah 2 minggu.', DATE_SUB(NOW(), INTERVAL 15 DAY)),
(3, 93, 5, 'Sangat puas, teksturnya ringan dan cepat meresap. Highly recommended!', DATE_SUB(NOW(), INTERVAL 114 DAY)),
(4, 93, 4, 'Teksturnya ringan dan mudah meresap. Cocok untuk pemakaian sehari-hari.', DATE_SUB(NOW(), INTERVAL 70 DAY)),
(5, 93, 4, 'Produknya bagus dan efektif, hanya butuh waktu sedikit lebih lama.', DATE_SUB(NOW(), INTERVAL 107 DAY)),
(1, 94, 5, 'Paling cocok di kulit sensitif saya. Tidak iritasi sama sekali.', DATE_SUB(NOW(), INTERVAL 75 DAY)),
(2, 94, 5, 'Kulit yang kusam jadi lebih cerah dan segar. Suka banget!', DATE_SUB(NOW(), INTERVAL 19 DAY)),
(3, 94, 5, 'Wajah jadi lebih glowing setelah pakai ini rutin. Terima kasih!', DATE_SUB(NOW(), INTERVAL 17 DAY)),
(4, 94, 4, 'Produknya bagus dan efektif, hanya butuh waktu sedikit lebih lama.', DATE_SUB(NOW(), INTERVAL 40 DAY)),
(5, 94, 3, 'Belum ada perubahan signifikan. Mungkin perlu waktu lebih lama.', DATE_SUB(NOW(), INTERVAL 116 DAY)),
(1, 95, 4, 'Produknya bagus dan efektif, hanya butuh waktu sedikit lebih lama.', DATE_SUB(NOW(), INTERVAL 116 DAY)),
(2, 95, 4, 'Suka dengan kandungannya, cocok di kulit kombinasi.', DATE_SUB(NOW(), INTERVAL 27 DAY)),
(3, 95, 5, 'Hasilnya kelihatan setelah seminggu pemakaian rutin. Bakal beli lagi!', DATE_SUB(NOW(), INTERVAL 86 DAY)),
(4, 95, 5, 'Sangat puas, teksturnya ringan dan cepat meresap. Highly recommended!', DATE_SUB(NOW(), INTERVAL 46 DAY)),
(5, 95, 4, 'Manfaatnya terasa nyata meski butuh konsistensi. Overall worth it.', DATE_SUB(NOW(), INTERVAL 80 DAY)),
(1, 96, 5, 'Pembelian terbaik saya! Benar-benar mengubah kondisi kulit.', DATE_SUB(NOW(), INTERVAL 119 DAY)),
(2, 96, 3, 'Teksturnya agak berat untuk kulit berminyak, tapi tetap aman dipakai.', DATE_SUB(NOW(), INTERVAL 111 DAY)),
(3, 96, 4, 'Teksturnya ringan dan mudah meresap. Cocok untuk pemakaian sehari-hari.', DATE_SUB(NOW(), INTERVAL 103 DAY)),
(4, 96, 5, 'Pembelian terbaik saya! Benar-benar mengubah kondisi kulit.', DATE_SUB(NOW(), INTERVAL 113 DAY)),
(5, 96, 4, 'Manfaatnya terasa nyata meski butuh konsistensi. Overall worth it.', DATE_SUB(NOW(), INTERVAL 4 DAY)),
(1, 97, 4, 'Teksturnya ringan dan mudah meresap. Cocok untuk pemakaian sehari-hari.', DATE_SUB(NOW(), INTERVAL 95 DAY)),
(2, 97, 5, 'Paling cocok di kulit sensitif saya. Tidak iritasi sama sekali.', DATE_SUB(NOW(), INTERVAL 101 DAY)),
(3, 97, 4, 'Manfaatnya terasa nyata meski butuh konsistensi. Overall worth it.', DATE_SUB(NOW(), INTERVAL 103 DAY)),
(4, 97, 4, 'Produk ori dan sesuai deskripsi. Kulit membaik setelah 3 minggu.', DATE_SUB(NOW(), INTERVAL 35 DAY)),
(5, 97, 5, 'Pembelian terbaik saya! Benar-benar mengubah kondisi kulit.', DATE_SUB(NOW(), INTERVAL 101 DAY)),
(1, 98, 5, 'Sangat puas, teksturnya ringan dan cepat meresap. Highly recommended!', DATE_SUB(NOW(), INTERVAL 49 DAY)),
(2, 98, 5, 'Produk ini luar biasa! Kulit terasa lebih lembap dan cerah setelah 2 minggu.', DATE_SUB(NOW(), INTERVAL 110 DAY)),
(3, 98, 3, 'Produknya original, tapi scent-nya kurang cocok di preferensi saya.', DATE_SUB(NOW(), INTERVAL 29 DAY)),
(4, 98, 4, 'Produk ori dan sesuai deskripsi. Kulit membaik setelah 3 minggu.', DATE_SUB(NOW(), INTERVAL 105 DAY)),
(5, 98, 5, 'Langsung terasa bedanya dari pemakaian pertama. Serum favorit baru!', DATE_SUB(NOW(), INTERVAL 45 DAY)),
(1, 99, 4, 'Bagus meski harganya sedikit mahal. Tapi kualitasnya sepadan.', DATE_SUB(NOW(), INTERVAL 106 DAY)),
(2, 99, 4, 'Produk ori dan sesuai deskripsi. Kulit membaik setelah 3 minggu.', DATE_SUB(NOW(), INTERVAL 29 DAY)),
(3, 99, 4, 'Produknya bagus dan efektif, hanya butuh waktu sedikit lebih lama.', DATE_SUB(NOW(), INTERVAL 85 DAY)),
(4, 99, 5, 'Hasilnya kelihatan setelah seminggu pemakaian rutin. Bakal beli lagi!', DATE_SUB(NOW(), INTERVAL 52 DAY)),
(5, 99, 5, 'Paling cocok di kulit sensitif saya. Tidak iritasi sama sekali.', DATE_SUB(NOW(), INTERVAL 36 DAY)),
(1, 100, 5, 'Sangat puas, teksturnya ringan dan cepat meresap. Highly recommended!', DATE_SUB(NOW(), INTERVAL 99 DAY)),
(2, 100, 4, 'Bagus meski harganya sedikit mahal. Tapi kualitasnya sepadan.', DATE_SUB(NOW(), INTERVAL 45 DAY)),
(3, 100, 5, 'Kulit yang kusam jadi lebih cerah dan segar. Suka banget!', DATE_SUB(NOW(), INTERVAL 52 DAY)),
(4, 100, 5, 'Kulit yang kusam jadi lebih cerah dan segar. Suka banget!', DATE_SUB(NOW(), INTERVAL 43 DAY)),
(5, 100, 3, 'Produknya oke, tapi hasilnya belum terlalu kelihatan di minggu pertama.', DATE_SUB(NOW(), INTERVAL 15 DAY));

UPDATE products p
SET
  reviews = (SELECT COUNT(*) FROM product_reviews WHERE product_id = p.id),
  rating  = (SELECT ROUND(AVG(rating), 1) FROM product_reviews WHERE product_id = p.id)
WHERE id BETWEEN 51 AND 100;

SELECT id, name, rating, reviews FROM products WHERE id BETWEEN 51 AND 60 ORDER BY id;
